#此工作流将对提取请求进行分类，并根据
在拉入请求中修改的路径数。
#
#要使用此工作流，您需要设置.github/labeler.yml
#具有配置的文件。有关详细信息，请参阅：
#https://github.com/actions/labeler

姓名:贴标机
在……之上:[pull_request_target]

工作:
标签:

run-on:ubuntu-最新
权限:
内容:读
拉式请求:写

步骤:
-uses:操作/标签@v4
和……一起:
repo-token:"${{secrets.GITHUB_TOKEN}}"
